// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ0ZOMjx4zZWDMoVjAZ7hCzq9WvdqjaBs',
    appId: '1:1097532101978:web:b93bc98293f3e116758f63',
    messagingSenderId: '1097532101978',
    projectId: 'todo-995ef',
    authDomain: 'todo-995ef.firebaseapp.com',
    storageBucket: 'todo-995ef.appspot.com',
    measurementId: 'G-B92EXTM9MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPDCZu8Pvcen17q6iJqT4TQF9wJc3c64U',
    appId: '1:1097532101978:android:ca5d0a8b456e5a4b758f63',
    messagingSenderId: '1097532101978',
    projectId: 'todo-995ef',
    storageBucket: 'todo-995ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Ts0viQnr4MLmGDmtuoeh-4brhEaPMy8',
    appId: '1:1097532101978:ios:5e21ef5dd7c653cf758f63',
    messagingSenderId: '1097532101978',
    projectId: 'todo-995ef',
    storageBucket: 'todo-995ef.appspot.com',
    iosClientId:
        '1097532101978-23mpcutfnm71vplv5sctl38b1pmta58v.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Ts0viQnr4MLmGDmtuoeh-4brhEaPMy8',
    appId: '1:1097532101978:ios:5e21ef5dd7c653cf758f63',
    messagingSenderId: '1097532101978',
    projectId: 'todo-995ef',
    storageBucket: 'todo-995ef.appspot.com',
    iosClientId:
        '1097532101978-23mpcutfnm71vplv5sctl38b1pmta58v.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
